### PR TITLE
Rename ChannelKeys -> Sign and generic it consistently

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Based on #789, this has really upset my OCD for some time, so needs fixing.

The `ChannelKeys` object really isn't about keys at all anymore,
its all about signing. At the same time, we rename the type aliases
used in traits from both `ChanKeySigner` and `Keys` to just
`ChanSigner`

### CODE REVIEW

File: lightning/src/chain/mod.rs [hunk 1]
```diff
@@ -69,7 +69,7 @@ pub trait Access: Send + Sync {
 /// [`PermanentFailure`]: channelmonitor/enum.ChannelMonitorUpdateErr.html#variant.PermanentFailure
 pub trait Watch: Send + Sync {
 	/// Keys needed by monitors for creating and signing transactions.
-	type Keys: ChannelKeys;
+	type ChanSigner: ChannelSigner;
```
Comment (jkczyz) [inline lightning/src/chain/mod.rs:72]: Not sure if you're warming to the using verbs for traits and nouns for types, but consider `trait Sign` and `type ChannelSigner: Sign` for consistency. Then you could dispense with abbreviated `ChanSigner`.

Comment (devrandom) [reply lightning/src/chain/mod.rs:72]: Considering the options in more detail:

 N | Trait | Type | Type Param
--- | --- | --- | ---
1 | ChannelSigner | InMemoryChannelSigner | ChanSigner
2 | Sign | InMemoryChannelSigner | ChannelSigner
3 | ChannelSign | InMemoryChannelSigner | ChannelSigner
4 | Sign | InMemorySigner | Signer

So 1 is this PR in its current state, 2 is what @jkczyz proposed.  3 seems to be a more consistent version of 2 which doesn't drop the word `Channel` on the trait.  We could go for 4 given that signing at the channel level is such a fundamental aspect of a Lightning node, so might as well be a bit less verbose.

I prefer 4 somewhat, but I don't feel strongly.

**Review by devrandom — APPROVED** [review]
ACK, but consider some variations on naming

File: lightning/src/chain/mod.rs (hunk 1 above)
Comment (TheBlueMatt) [reply lightning/src/chain/mod.rs:72]: Hmm, the problem I have with Sign is it doesn't really fully capture what's going on - it's a channel-specific thing that signs. If we moved it to channel::Sign it'd be more like chain::Watch but I'm not sure it makes sense there.

Comment (jkczyz) [reply lightning/src/chain/mod.rs:72]: I tend to agree with @devrandom in that "channel" is fundamental so could be dropped. I'd favor (4) but with slight variation.

IMO, it is redundant when used as the type parameter to `Channel`.

```rust
pub(super) struct Channel<ChanSigner: ChannelSigner> {
}

impl<ChanSigner: ChannelSigner> Channel<ChanSigner> {
}
```

That it is for a specific channel could be made clear in the documentation and is enforced by it being a type parameter for `Channel` and `ChannelMonitor`.

However, for parameterizing types where what signing pertains to isn't clear, the type parameter could be the more specific `ChannelSigner` instead `Signer` (e.g., in `Watch`).

Comment (TheBlueMatt) [reply lightning/src/chain/mod.rs]: Ok, I think I did this everywhere, let me know if I missed any cases.

File: lightning-persister/src/lib.rs [hunk 2]
```diff
@@ -45,7 +45,7 @@ trait DiskWriteable {
 	fn write(&self, writer: &mut fs::File) -> Result<(), Error>;
 }
 
-impl<ChanSigner: ChannelKeys> DiskWriteable for ChannelMonitor<ChanSigner> {
+impl<ChanSigner: Sign> DiskWriteable for ChannelMonitor<ChanSigner> {
```
Comment (jkczyz) [inline lightning-persister/src/lib.rs:48]: `Signer` should be sufficient here.

File: lightning-persister/src/lib.rs [hunk 3]
```diff
@@ -130,7 +130,7 @@ impl FilesystemPersister {
 	}
 }
 
-impl<ChanSigner: ChannelKeys + Send + Sync> channelmonitor::Persist<ChanSigner> for FilesystemPersister {
+impl<ChanSigner: Sign + Send + Sync> channelmonitor::Persist<ChanSigner> for FilesystemPersister {
```
Comment (jkczyz) [inline lightning-persister/src/lib.rs:133]: Maybe here too?

Tangentially, I wonder if this type parameter should really be moved to the functions where it is clearer. Is it required at the struct level in order to work with another struct that is parameterized by this? Or is the compiler smart enough to make the determination?

File: lightning/src/chain/channelmonitor.rs [hunk 4]
```diff
@@ -2253,7 +2253,7 @@ impl<ChanSigner: ChannelKeys> ChannelMonitor<ChanSigner> {
 /// transaction and losing money. This is a risk because previous channel states
 /// are toxic, so it's important that whatever channel state is persisted is
 /// kept up-to-date.
-pub trait Persist<Keys: ChannelKeys>: Send + Sync {
+pub trait Persist<Keys: Sign>: Send + Sync {
```
Comment (jkczyz) [inline lightning/src/chain/channelmonitor.rs:2256]: What should we do for cases where `Keys` was used as a type parameter? Maybe best to standardize as `Signer`.

File: lightning/src/chain/mod.rs [hunk 5]
```diff
@@ -69,7 +69,7 @@ pub trait Access: Send + Sync {
 /// [`PermanentFailure`]: channelmonitor/enum.ChannelMonitorUpdateErr.html#variant.PermanentFailure
 pub trait Watch: Send + Sync {
 	/// Keys needed by monitors for creating and signing transactions.
-	type Keys: ChannelKeys;
+	type ChanSigner: Sign;
```
Comment (jkczyz) [inline lightning/src/chain/mod.rs:72]: Similarly here only for using an associated type vs function type parameter.

File: lightning/src/ln/chan_utils.rs [hunk 6]
```diff
@@ -8,8 +8,8 @@
 // licenses.
 
 //! Various utilities for building scripts and deriving keys related to channels. These are
-//! largely of interest for those implementing chain::keysinterface::ChannelKeys message signing
-//! by hand.
+//! largely of interest for those implementing chain::keysinterface::ChannelSigner message
```
Comment (jkczyz) [inline lightning/src/ln/chan_utils.rs:11]: Should this be `Sign`?

**Review by jkczyz — COMMENTED** [review]
I'd prefer `ChannelSigner` over `ChanSigner` as the shortened version was introduced primarily to avoid conflicting with the trait name. But that is no longer a problem. I also find the "chan" is a little too close to "chain" when reading.

File: lightning-persister/src/lib.rs (hunk 3 above)
Comment (TheBlueMatt) [reply lightning-persister/src/lib.rs:133]: Hmm, this seems to not have any other Channel context.

As to the question about functions, I believe its required in this context because `ChannelMonitor` stores a signer in the struct, not just accepting it as a parameter to a function.

File: lightning/src/chain/channelmonitor.rs (hunk 4 above)
Comment (TheBlueMatt) [reply lightning/src/chain/channelmonitor.rs:2256]: Oops, my regexes missed those ones.

File: lightning/src/chain/mod.rs (hunk 5 above)
Comment (TheBlueMatt) [reply lightning/src/chain/mod.rs:72]: Hmm, so this doesn't make sense as a function parameter - users don't ever want to receive arbitrary `ChannelMonitor`s with unknown signer while serializing. That said, this probably shouldn't be an associated type - a `Watch<A>` is a different type from a `Watch<B>` and a single struct could (though probably won't) implement both.

File: lightning-persister/src/lib.rs (hunk 3 above)
Comment (jkczyz) [reply lightning-persister/src/lib.rs:133]: For the context, I was seeing the module qualifier `channelmonitor` and the use below parameterizing `ChannelMonitor`. I don't feel too strongly about this, though.

**Comment by jkczyz** [comment]
> I'd prefer `ChannelSigner` over `ChanSigner` as the shortened version was introduced primarily to avoid conflicting with the trait name. But that is no longer a problem. I also find the "chan" is a little too close to "chain" when reading.

If it's not too much trouble, changing this only touches a few files mostly where "chain" is used.

**Review by jkczyz — APPROVED** [review]

File: lightning-persister/src/lib.rs (hunk 3 above)
Comment (TheBlueMatt) [reply lightning-persister/src/lib.rs:133]: Ah. Yea, I see your point. I don't care either way now, and its more work to change it :).

**Comment by TheBlueMatt** [comment]
Rebased.

**Comment by TheBlueMatt** [comment]
Also threw in bindings updates cause they are trivial.

File: lightning-c-bindings/demo.cpp [hunk 7]
```diff
@@ -363,7 +363,7 @@ int main() {
 		LDK::PeerManager net1 = PeerManager_new(std::move(msg_handler1), node_secret1, &random_bytes.data, logger1);
 
 		// Demo getting a channel key and check that its returning real pubkeys:
-		LDK::ChannelKeys chan_keys1 = keys_source1->get_channel_keys(keys_source1->this_arg, false, 42);
+		LDK::Sign chan_keys1 = keys_source1->get_channel_signer(keys_source1->this_arg, false, 42);
```
Comment (jkczyz) [inline lightning-c-bindings/demo.cpp:366]: s/chan_keys1/signer1

File: lightning-c-bindings/demo.cpp [hunk 8]
```diff
@@ -634,5 +634,5 @@ int main() {
 	memset(&sk, 42, 32);
 	LDKThirtyTwoBytes kdiv_params;
 	memset(&kdiv_params, 43, 32);
-	LDK::InMemoryChannelKeys keys = InMemoryChannelKeys_new(sk, sk, sk, sk, sk, random_bytes, 42, kdiv_params);
+	LDK::InMemorySigner keys = InMemorySigner_new(sk, sk, sk, sk, sk, random_bytes, 42, kdiv_params);
```
Comment (jkczyz) [inline lightning-c-bindings/demo.cpp:637]: s/keys/signer

**Review by jkczyz — COMMENTED** [review]
Getting some errors when running `genbindings.sh`:

```term
++ rustc --version --verbose
++ grep host:
+ HOST_PLATFORM='host: x86_64-apple-darwin'
+ '[' 'host: x86_64-apple-darwin' = 'host: x86_64-apple-darwin' ']'
+ sed -i '' 's/typedef LDKnative.*Import.*LDKnative.*;//g' include/lightning.h
+ CFLAGS='-Wall -Wno-nullability-completeness -pthread'
+ gcc -Wall -Wno-nullability-completeness -pthread -Wall -g -pthread demo.c target/debug/libldk.a -ldl
In file included from demo.c:2:
./include/lightning.h:1605:18: error: expected member name or ';' after declaration specifiers
   LDKHTLCUpdate 0;
   ~~~~~~~~~~~~~ ^
./include/lightning.h:1605:17: error: expected ';' at end of declaration list
   LDKHTLCUpdate 0;
                ^
                ;
./include/lightning.h:1609:16: error: expected member name or ';' after declaration specifiers
   LDKOutPoint 0;
   ~~~~~~~~~~~ ^
./include/lightning.h:1609:15: error: expected ';' at end of declaration list
   LDKOutPoint 0;
              ^
              ;
./include/lightning.h:1724:38: error: expected member name or ';' after declaration specifiers
   LDKDelayedPaymentOutputDescriptor 0;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
./include/lightning.h:1724:37: error: expected ';' at end of declaration list
   LDKDelayedPaymentOutputDescriptor 0;
                                    ^
                                    ;
./include/lightning.h:1728:37: error: expected member name or ';' after declaration specifiers
   LDKStaticPaymentOutputDescriptor 0;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
./include/lightning.h:1728:36: error: expected ';' at end of declaration list
   LDKStaticPaymentOutputDescriptor 0;
                                   ^
                                   ;
./include/lightning.h:2385:16: error: expected member name or ';' after declaration specifiers
   LDKAPIError 0;
   ~~~~~~~~~~~ ^
./include/lightning.h:2385:15: error: expected ';' at end of declaration list
   LDKAPIError 0;
              ^
              ;
./include/lightning.h:2389:35: error: expected member name or ';' after declaration specifiers
   LDKCVec_CResult_NoneAPIErrorZZ 0;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
./include/lightning.h:2389:34: error: expected ';' at end of declaration list
   LDKCVec_CResult_NoneAPIErrorZZ 0;
                                 ^
                                 ;
./include/lightning.h:2393:22: error: expected member name or ';' after declaration specifiers
   LDKCVec_APIErrorZ 0;
   ~~~~~~~~~~~~~~~~~ ^
./include/lightning.h:2393:21: error: expected ';' at end of declaration list
   LDKCVec_APIErrorZ 0;
                    ^
                    ;
./include/lightning.h:2397:35: error: expected member name or ';' after declaration specifiers
   LDKCVec_CResult_NoneAPIErrorZZ 0;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
./include/lightning.h:2397:34: error: expected ';' at end of declaration list
   LDKCVec_CResult_NoneAPIErrorZZ 0;
                                 ^
                                 ;
16 errors generated.
```

**Comment by TheBlueMatt** [comment]
> ./include/lightning.h:1605:18: error: expected member name or ';' after declaration specifiers
>    LDKHTLCUpdate 0;
>    ~~~~~~~~~~~~~ ^
   
 Hmm, that isnt how the header looks for me. Can you try updating your cbindgen (or maybe I need to update mine?)

**Comment by jkczyz** [comment]
> > ./include/lightning.h:1605:18: error: expected member name or ';' after declaration specifiers
> > LDKHTLCUpdate 0;
> 
> Hmm, that isnt how the header looks for me. Can you try updating your cbindgen (or maybe I need to update mine?)

Working on 0.17.0. I was on 0.14.4.

**Comment by devrandom** [comment]
Perhaps also rename `chan_keys` in several places (but not all places, it's used for tx keys in some spots).

Similarly for `Channel.holder_keys` and `Channel.get_keys`.

Also, we might consider renaming `KeysInterface` / `KeysManager`, but should probably do it in a followup in the interest of keeping PRs small.

Or if you want, I can do all this in a followup.

ACK on current

**Comment by TheBlueMatt** [comment]
Squashed earlier fixup commits and added a commit to rename the missing `chan_keys` objects.

**Comment by devrandom** [comment]
ACK https://github.com/rust-bitcoin/rust-lightning/pull/799/commits/4b6f0a3b268330adffbbfe9471fab577e2be4864

**Comment by jkczyz** [comment]
ACK 4b6f0a3b268330adffbbfe9471fab577e2be4864
